# Auth Service Configuration
server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: nexuscart
    password: nexuscart123
